name: 'Run Julia package tests'
description: 'Run the tests in a Julia package'
author: 'David Anthoff'
inputs:
  codecov:
    description: 'Coverage results upload to codecov.'
    required: false
    default: 'true'
  coveralls:
    description: 'Coverage results upload to coveralls.'
    required: false
    default: 'true'
runs:
  using: 'node12'
  main: 'lib/main.js'
